Revert "Revert "Review""
peeercyyy/stellar-burgers pull request #3
Opened 2024-07-29 16:32 UTC by peeercyyy

Reverts peeercyyy/stellar-burgers#2

2024-07-29 18:23 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Страница `/feed` должна быть доступна всем пользователям, а не только авторизованным.

- <https://disk.yandex.com/i/G3O6E66wbkIMZw> - Иконки должны быть белого цвета, только у активной ссылки;

- <https://disk.yandex.com/i/QUs2-rSWjCTpjQ>, <https://disk.yandex.com/i/dZpnLVDMuc0xDQ> - У вас не отображаются заказы на странице `/feed` и `/profile/orders`.

- <https://disk.yandex.com/i/6HhNVdK4Ru1IvA> - В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива.

### **_Более мелкие замечания, отмечены в коде._**

2024-07-29 18:23 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.tsx
> +    constructorItems.ingredients.forEach((i) => data.push(i._id));
**Надо исправить:**

В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива

2024-07-29 18:23 UTC, ArslanMustafin commented on src/components/protected-route/protected-route.tsx
> +};
**Надо исправить:**

Вы должны тут просто дождаться получение пользователя и проверить авторизован он или нет.

Оптимальный пример компонента ProtectRoute:

```js
export const ProtectedRoute = ({ onlyUnAuth = false, children }) => {
  const isAuthChecked = useSelector((state) => state.user.isAuthChecked);
  const user = useSelector((state) => state.user.data);
  const location = useLocation();

  if (!isAuthChecked) {
    return <Preloader />;
  }

  if (onlyUnAuth && user) {
    const { from } = location.state || { from: { pathname: "/" } };
    return <Navigate to={from} />;
  }

  if (!onlyUnAuth && !user) {
    return (
      <Navigate
        to="/login"
        state={{ from: location }}
      />
    );
  }

  return children;
};

// использование

<Route
  path="/register"
  element={
    <ProtectedRoute onlyUnAuth={true}>
      <Register />
    </ProtectedRoute>
  }
/>

<Route
  path="/profile"
  element={
    <ProtectedRoute>
      <Profile />
    </ProtectedRoute>
  }
/>
```

Вам не хватает вот этой проверки, поэтому у вас и мелькают защищённые страницы.

```js
if (!isAuthChecked) {
  return <Preloader />;
}
```

`isAuthChecked` - это просто флаг, который показывает, выполнился ли запрос на получения пользователя или ещё нет. Важен сам процесс, если он завершён, то флаг будет `true` (не зависит от результат, т.к. он будет `true` в любом случае, даже если будет ошибка), если он ещё не произошёл, то будет `false`.

2024-07-29 18:23 UTC, ArslanMustafin commented on src/pages/constructor-page/constructor-page.tsx
> +  }, []);
**Надо исправить:**

Лучше всего это вызов делать в компоненте `app`, а во всех других убрать.

2024-07-31 13:55 UTC, peeercyyy commented on src/components/burger-constructor/burger-constructor.tsx
> +    constructorItems.ingredients.forEach((i) => data.push(i._id));
исправлено

2024-07-31 13:55 UTC, peeercyyy commented on src/components/protected-route/protected-route.tsx
> +};
исправлено

2024-07-31 13:55 UTC, peeercyyy commented on src/pages/constructor-page/constructor-page.tsx
> +  }, []);
исправлено

2024-07-31 13:57 UTC, peeercyyy commented
> ## Code Review
> Здравствуйте!
> 
> Отличная работа. 🔥
> 
> ### **Вы молодец!**
> * Сборка и запуск проекта выполняются без ошибок;
> * Есть модальные окна;
> * Данные получают с сервера;
> * Теперь у вас есть роутинг;
> * Есть регистрация и авторизация;
> 
> ### **Но есть несколько замечаний, которые нужно исправить:**
> * Страница `/feed` должна быть доступна всем пользователям, а не только авторизованным.
> * https://disk.yandex.com/i/G3O6E66wbkIMZw - Иконки должны быть белого цвета, только у активной ссылки;
> * https://disk.yandex.com/i/QUs2-rSWjCTpjQ, https://disk.yandex.com/i/dZpnLVDMuc0xDQ - У вас не отображаются заказы на странице `/feed` и `/profile/orders`.
> * https://disk.yandex.com/i/6HhNVdK4Ru1IvA - В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива.
> 
> ### **_Более мелкие замечания, отмечены в коде._**

У меня все заказы отображаются на страницах

![image](https://github.com/user-attachments/assets/9bae75ce-c82c-4305-aef3-e1f173ed9854)
![image](https://github.com/user-attachments/assets/148239fa-7b4e-418b-bf0c-fe06b1b6c040)

2024-08-01 05:19 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-08-01 05:30 UTC, merged